CREATE TABLE IF NOT EXISTS `CATEGORIA` (
  `cat_id` INT NOT NULL AUTO_INCREMENT,
  `cat_nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`cat_id`)
);

CREATE TABLE IF NOT EXISTS `STATUS` (
  `sta_id` INT NOT NULL AUTO_INCREMENT,
  `sta_nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`sta_id`)
);

CREATE TABLE IF NOT EXISTS `SISTEMA` (
  `sis_id` INT NOT NULL AUTO_INCREMENT,
  `sis_nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`sis_id`)
);

CREATE TABLE IF NOT EXISTS `CLIENTE` (
  `cli_id` INT NOT NULL AUTO_INCREMENT,
  `cli_nome` VARCHAR(50) NOT NULL,
  `cli_celular` VARCHAR(20) NOT NULL,
  `cli_email` VARCHAR(100) NOT NULL,
  `cli_acesso` VARCHAR(20) NOT NULL,
  `cli_sistema` INT NOT NULL,
  PRIMARY KEY (`cli_id`),
  FOREIGN KEY (`cli_sistema`) REFERENCES `SISTEMA`(`sis_id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `ATENDIMENTO` (
  `ate_id` INT NOT NULL AUTO_INCREMENT,
  `ate_cliente` INT NOT NULL,
  `ate_data_criacao` DATE NOT NULL DEFAULT CURRENT_DATE,
  `ate_categoria` INT NOT NULL,
  `ate_status` INT NOT NULL,
  `ate_descricao` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`ate_id`),
  FOREIGN KEY (`ate_cliente`) REFERENCES `CLIENTE`(`cli_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`ate_categoria`) REFERENCES `CATEGORIA`(`cat_id`) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`ate_status`) REFERENCES `STATUS`(`sta_id`) ON DELETE CASCADE ON UPDATE CASCADE
);